# Core tools and the four language servers used by Neovim.
brew "stow"
brew "git"
brew "neovim"
brew "herdr"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "python"
brew "powerlevel10k"
brew "tmux"
brew "pyright"
brew "typescript"
brew "gopls"
brew "lua-language-server"
brew "go"
cask "visual-studio-code"
